# Generated by Django 2.1.4 on 2019-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(choices=[('reddit', 'Reddit'), ('newsapi', 'NewsAPI')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAPI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('newsaggregator.newssource',),
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('newsaggregator.newssource',),
        ),
    ]
