# Generated by Django 2.1.4 on 2019-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='source_name',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('newsapi', 'NewsAPI')], max_length=200, unique=True),
        ),
    ]
